../RTL/alu.v
../RTL/alu_control.v
../RTL/branch_unit.v
../RTL/control_unit.v
../RTL/cpu.v
../RTL/immediate_extend_unit.v
../RTL/mux_2.v
../RTL/pc.v
../RTL/reg_arstn.v
../RTL/reg_arstn_en.v
../RTL/register_file.v
../RTL/sram.v
../RTL/cpu_tb.v
../RTL/saed32sram_mod.v
../RTL/mux_3.v
../RTL/forward_unit.v
../RTL/hazard_detection.v
../RTL/hazard_mux.v